services:
  firebase:
    build: ./docker/firebase/
    command: emulators:start
    ports:
      - "4000:4000"
      - "4400:4400"
      - "4500:4500"
      - "5001:5001"
      - "8080:8080"
      - "9099:9099"
    volumes:
      - .:/home/cloudsdk
  tsukota:
    build: ./docker/tsukota/
    env_file: ./packages/tsukota/.env
    ports:
      - "19000:19000"
    tty: true
    volumes:
      - .:/home/node
