services:
  firebase:
    build: ./docker/firebase/
    entrypoint: /bin/bash
    ports:
      - "4000:4000"
      - "4400:4400"
      - "4500:4500"
      - "8080:8080"
      - "9099:9099"
    tty: true
    volumes:
      - .:/home/cloudsdk

